### ISSUE TITLE
RD console "bluescreens" when importing designs

### ISSUE THREAD

**Issue by MitztheKat** [Yawn-Wider/YWPolarisVore#1205]
#### Brief description of the issue
I can't use the RD console, it's stuck. I can't remove the disk either.

#### What you expected to happen
Stuff to get imported onto the disk I shoved in the console, which i would later export to the engineering department

#### What actually happened
TypeError: Unable to get property 'map' of undefined or null reference
   at u (http://127.0.0.1:55536/tmp4188/tgui.bundle.js:1:565754)
   at Me (http://127.0.0.1:55536/tmp4188/tgui-common.bundle.js:1:173557)
   at Anonymous function (http://127.0.0.1:55536/tmp4188/tgui-common.bundle.js:1:173825)
   at Ae (http://127.0.0.1:55536/tmp4188/tgui-common.bundle.js:1:173803)
   at Pe (http://127.0.0.1:55536/tmp4188/tgui-common.bundle.js:1:174851)
   at Ie (http://127.0.0.1:55536/tmp4188/tgui-common.bundle.js:1:174690)
   at Ae (http://127.0.0.1:55536/tmp4188/tgui-common.bundle.js:1:173667)
   at Ie (http://127.0.0.1:55536/tmp4188/tgui-common.bundle.js:1:174656)
   at Ae (http://127.0.0.1:55536/tmp4188/tgui-common.bundle.js:1:173667)
   at Pe (http://127.0.0.1:55536/tmp4188/tgui-common.bundle.js:1:174851)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; HCTE; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"mitz","interface":"ResearchConsole","window":{"key":"[0x200a6ce]-main","size":null,"fancy":1,"locked":0}}

#### Steps to reproduce
- research some stuff
- insert component design disk into RD console
- download designs
- 
![image](https://user-images.githubusercontent.com/29964282/138532905-72aa3c90-f7c6-4dc9-ab94-fbbeb517e3cc.png)

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: 8f080a04f7c35b303c6c3edaa79887d9d1a2ce52
TGS version: 4.15.6
DMAPI version: 5.1.1 
 
#### Anything else you may wish to add:
- ... help?

**Comment by izac112** [comment]
https://github.com/VOREStation/VOREStation/issues/15263 appears to be fixed now
